// <auto-generated />
namespace RecipeTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addadvertiserNametoads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadvertiserNametoads));
        
        string IMigrationMetadata.Id
        {
            get { return "202504180504399_add-advertiserName-to-ads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
