// <auto-generated />
namespace RecipeTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addadviewlogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadviewlogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202504170753543_add-adviewlog-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
