// <auto-generated />
namespace RecipeTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addFK_AdViewLog_to_Ad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFK_AdViewLog_to_Ad));
        
        string IMigrationMetadata.Id
        {
            get { return "202504200424459_addFK_AdViewLog_to_Ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
