// <auto-generated />
namespace RecipeTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addcommentstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcommentstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202503220346164_add-comments-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
