// <auto-generated />
namespace RecipeTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initschema));
        
        string IMigrationMetadata.Id
        {
            get { return "202504210418111_init-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
